name: examenflutteriit
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutterfire_cli: ^0.2.7
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.0
  firebase_messaging: ^14.7.19
  flutter_native_splash:
  flutter_launcher_icons:
  get_storage: ^2.1.1
  awesome_snackbar_content: ^0.1.3
  persistent_bottom_nav_bar: ^5.0.2
  provider: ^6.1.2
  settings_ui: ^2.0.2
  line_awesome_flutter: ^2.0.0
  syncfusion_flutter_datepicker: ^25.1.40
  lottie:
  http:
  flutter_localizations:
    sdk: flutter




flutter_icons:
  image_path: "assets/teacher.png"
  android: true
  ios: true


# flutter_native_splash-development.yaml
flutter_native_splash:
  color: "#ffffff"
  image: assets/teacher.png
  branding: assets/teacher.png
  color_dark: "#121212"
  image_dark: assets/teacher.png
  branding_dark: assets/teacher.png

  android_12:
    image: assets/teacher.png
    icon_background_color: "#ffffff"
    image_dark: assets/teacher.png
    icon_background_color_dark: "#121212"

  web: false

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/images/google_icon.png
    - assets/

