// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfA9cP9DYsM-GNMM8SGNrc9qv4o1023hA',
    appId: '1:77606191095:web:4c3a0093b638a440fef8f2',
    messagingSenderId: '77606191095',
    projectId: 'iitcoursoir-d5244',
    authDomain: 'iitcoursoir-d5244.firebaseapp.com',
    storageBucket: 'iitcoursoir-d5244.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClLsMn8VdwBQKE2mCQeiV7lP_VRYwlZmU',
    appId: '1:77606191095:android:69899f7dc5b9301efef8f2',
    messagingSenderId: '77606191095',
    projectId: 'iitcoursoir-d5244',
    storageBucket: 'iitcoursoir-d5244.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2t1R-MxXdx15UsijtSos4JOErAva25mo',
    appId: '1:77606191095:ios:a4bc54d37ed1f2f2fef8f2',
    messagingSenderId: '77606191095',
    projectId: 'iitcoursoir-d5244',
    storageBucket: 'iitcoursoir-d5244.appspot.com',
    iosBundleId: 'com.example.examenflutteriit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2t1R-MxXdx15UsijtSos4JOErAva25mo',
    appId: '1:77606191095:ios:cc91a5f3b634a20afef8f2',
    messagingSenderId: '77606191095',
    projectId: 'iitcoursoir-d5244',
    storageBucket: 'iitcoursoir-d5244.appspot.com',
    iosBundleId: 'com.example.examenflutteriit.RunnerTests',
  );
}
